//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class app_setting
    {
        public int id { get; set; }
        public string websitetitle { get; set; }
        [DisplayName("Upload Image")]
        public string websitelogopath { get; set; }
        [DisplayName("Upload Image")]
        public string footerlogopath { get; set; }
        [DisplayName("Upload Image")]
        public string faviconpath { get; set; }
        [DisplayName("Upload Image")]
        public string applogopath { get; set; }
        [DisplayName("Upload Image")]
        public string mblmenupath { get; set; }
        public string webfooter { get; set; }
        public string copyright { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase ImageFile1 { get; set; }
        public HttpPostedFileBase ImageFile2 { get; set; }
        public HttpPostedFileBase ImageFile3 { get; set; }
        public HttpPostedFileBase ImageFile4 { get; set; }
    }
}
