//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_info
    {
        public int id { get; set; }
        public string Content { get; set; }
        public string address { get; set; }
        public string phn_one { get; set; }
        public string phn_two { get; set; }
        public string email { get; set; }
        public string website_link { get; set; }
    }
}
