//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basicEntities : DbContext
    {
        public basicEntities()
            : base("name=basicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<contact_info> contact_info { get; set; }
        public virtual DbSet<Email_setting> Email_setting { get; set; }
        public virtual DbSet<app_setting> app_setting { get; set; }
        public virtual DbSet<tbl_news> tbl_news { get; set; }
    }
}
