//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_setting
    {
        public int id { get; set; }
        public string smtp_protocol { get; set; }
        public string smtp_host { get; set; }
        public Nullable<int> smtp_port { get; set; }
        public string smtp_username { get; set; }
        public string smtp_pass { get; set; }
        public string smtp_mailtype { get; set; }
        public string smtp_charset { get; set; }
    }
}
