//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    using System.Web.Mvc;

    public partial class tbl_news
    {
        public int nid { get; set; }
        public string short_headline { get; set; }
        public string headline { get; set; }
        public string desc { get; set; }
        
        public string ImageTitle { get; set; }
        [DisplayName("Upload Image")]
        public string ImagePath { get; set; }
        public string Alttext { get; set; }
        public int categoryid { get; set; }
        //public List<category> categorylist { get; set; }
        public IEnumerable<SelectListItem> categorylist { get; set; }
        //public List<category> categorylist { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
